"""create_checkpoints_and_skipped_suggestions_tables

Revision ID: 950cffb2c67c
Revises: a1b2c3d4e5f6
Create Date: 2026-09-15 16:16:29.195946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950cffb2c67c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_checkpoints',
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('last_processed_id', sa.BigInteger(), nullable=False),
    sa.Column('total_processed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('skipped_suggestions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('suggestion_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('skipped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skipped_suggestions_suggestion_id'), 'skipped_suggestions', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skipped_suggestions_suggestion_id'), table_name='skipped_suggestions')
    op.drop_table('skipped_suggestions')
    op.drop_table('ingestion_checkpoints')
    # ### end Alembic commands ###
