"""create_suggestions_table

Revision ID: fd89a3de9dea
Revises: 
Create Date: 2026-09-12 13:50:45.464964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd89a3de9dea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('scrutiny', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shamsi_date', sa.String(length=10), nullable=True),
    sa.Column('context_title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status_id >= 1 AND status_id <= 5', name='ck_suggestions_status_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_context_title'), 'suggestions', ['context_title'], unique=False)
    op.create_index(op.f('ix_suggestions_shamsi_date'), 'suggestions', ['shamsi_date'], unique=False)
    op.create_index('ix_suggestions_status_context', 'suggestions', ['status_id', 'context_title'], unique=False)
    op.create_index(op.f('ix_suggestions_status_id'), 'suggestions', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestions_status_id'), table_name='suggestions')
    op.drop_index('ix_suggestions_status_context', table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_shamsi_date'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_context_title'), table_name='suggestions')
    op.drop_table('suggestions')
    # ### end Alembic commands ###
